# Generated by Django 3.2.7 on 2022-03-15 17:12

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CocoaContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
            ],
        ),
    ]
